### ISSUE TITLE
Using gem with nginx and unix socket

### ISSUE THREAD

**Issue by maxvipon** [lucassus/mongo_browser#112]
Is there a way to somehow configure gem and use It with unix socket instead localhost:5678 and nginx as proxy?

**Comment by lucassus** [comment]
mongo_browser is a standard rack application so you should be able to deploy it on the nginx server.
Here you can find an example how to do it http://stackoverflow.com/questions/13030149/how-to-deploy-ruby-rack-app-with-nginx
Let me know in case of any problems.

**Comment by maxvipon** [comment]
Ok, and what about using unix socket instead port? By the way, how can I configure mongodb hostname because It located on another machine?
